// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: file.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Iwe_SaveMessage_FullMethodName = "/apigrps.iwe/SaveMessage"
)

// IweClient is the client API for Iwe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IweClient interface {
	SaveMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type iweClient struct {
	cc grpc.ClientConnInterface
}

func NewIweClient(cc grpc.ClientConnInterface) IweClient {
	return &iweClient{cc}
}

func (c *iweClient) SaveMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Iwe_SaveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IweServer is the server API for Iwe service.
// All implementations must embed UnimplementedIweServer
// for forward compatibility.
type IweServer interface {
	SaveMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedIweServer()
}

// UnimplementedIweServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIweServer struct{}

func (UnimplementedIweServer) SaveMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMessage not implemented")
}
func (UnimplementedIweServer) mustEmbedUnimplementedIweServer() {}
func (UnimplementedIweServer) testEmbeddedByValue()             {}

// UnsafeIweServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IweServer will
// result in compilation errors.
type UnsafeIweServer interface {
	mustEmbedUnimplementedIweServer()
}

func RegisterIweServer(s grpc.ServiceRegistrar, srv IweServer) {
	// If the following call pancis, it indicates UnimplementedIweServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Iwe_ServiceDesc, srv)
}

func _Iwe_SaveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IweServer).SaveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Iwe_SaveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IweServer).SaveMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Iwe_ServiceDesc is the grpc.ServiceDesc for Iwe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Iwe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apigrps.iwe",
	HandlerType: (*IweServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveMessage",
			Handler:    _Iwe_SaveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file.proto",
}
